import assert from "node:assert/strict";
import { loadLib } from "./tsload.mjs";
const { landedCost, parseCosts, EMPTY_COSTS } = await loadLib("landedCost");
const { allocateCosts, allocateAmount } = await loadLib("landedCost");
assert.equal(landedCost(100, 20, { ...EMPTY_COSTS, freight: 0.1, insurance: 0.2 }).landed, 120.3);
assert.equal(landedCost(0, 0, EMPTY_COSTS).landedRatePct, 0);
assert.equal(landedCost(100, 20, { ...EMPTY_COSTS, freight: 10 }).landed, 130);
for (const invalid of [-1, Infinity, NaN, "12", 0.001, 1e10]) {
  assert.throws(() => parseCosts({ ...EMPTY_COSTS, freight: invalid }));
}
assert.throws(() => parseCosts(null));
assert.throws(() => parseCosts({}));
assert.deepEqual(parseCosts(EMPTY_COSTS), EMPTY_COSTS);
const fx = { ...EMPTY_COSTS, freight: 100, insurance: 0.1, currency: "EUR", usdRate: 1.125, rateDate: "2026-09-22", rateSource: "Fixture bank quote", allocation: "value" };
assert.equal(landedCost(200, 20, fx).totalExtras, 112.61);
assert.equal(landedCost(200, 20, fx).landed, 332.61);
for (const change of [{ usdRate: 0 }, { usdRate: Infinity }, { rateDate: "2026-02-30" }, { rateSource: "" }, { currency: "NOT" }, { currency: "USD", usdRate: 2 }]) assert.throws(() => parseCosts({ ...fx, ...change }));
assert.deepEqual(allocateAmount(0.01, [1, 1, 1]), [0.01, 0, 0]);
assert.deepEqual(allocateAmount(0.05, [0, 0, 0]), [0.02, 0.02, 0.01]);
const allocated = allocateCosts([{ id: "a", sku: "A", value: 100, duty: 10 }, { id: "b", sku: "B", value: 300, duty: 30 }], { ...EMPTY_COSTS, freight: 10 }, 4);
assert.deepEqual(allocated.map((l) => l.landed), [113.5, 340.5]);
assert.equal(allocated.reduce((n, l) => n + l.additional_costs, 0), 10);
assert.equal(allocateCosts([{ id: "a", sku: null, value: 100, duty: null }], EMPTY_COSTS, 1)[0].landed, null);
const proof = await loadLib("auditProof");
const model = await loadLib("auditModel");
const engine = { summary: { mpf: 1, dataset_revision: "fixture", assumptions: [] }, lines: [{ row: 1, sku: "a", description: "Product", country: "China", hts: "1234.56.78", status: "ready", suggested: [{ hts: "1234.56.78", reasoning: "Matched material", rulings: [{ ruling: "N000001", subject: "Fixture precedent", date: "2020-01-01", revoked: false, url: "https://rulings.cbp.gov/ruling/N000001", excerpt: "Material description" }] }] }] };
const body = proof.signedBodyFromEngine(engine);
const signature = proof.signAudit(body, "test-secret");
assert.equal(proof.verifyAudit({ ...body, lines: body.lines.map(model.projectLine) }, signature, "test-secret"), true, "evidence projection must be idempotent");
assert.equal(body.lines[0].evidence.rulings[0].excerpt, "Material description");
body.lines[0].evidence.rulings[0].excerpt = "Tampered";
assert.equal(proof.verifyAudit(body, signature, "test-secret"), false, "evidence edits invalidate the audit proof");
console.log("Landed cost: rounding, totals, zero-value and invalid-input checks passed.");
const { sameOrigin } = await loadLib("requestOrigin");
const configuredSite = process.env.SITE_URL;
delete process.env.SITE_URL;
assert.equal(sameOrigin(new Request("http://localhost:3478", { headers: { host: "127.0.0.1:3478", origin: "http://127.0.0.1:3478" } })), true);
assert.equal(sameOrigin(new Request("http://localhost:3478", { headers: { host: "127.0.0.1:3478", origin: "https://attacker.test" } })), false);
assert.equal(sameOrigin(new Request("http://localhost:3478")), false);
process.env.SITE_URL = "https://example.test";
assert.equal(sameOrigin(new Request("http://localhost:3478", { headers: { origin: "https://example.test" } })), true);
assert.equal(sameOrigin(new Request("http://localhost:3478", { headers: { origin: "http://example.test" } })), false);
if (configuredSite === undefined) delete process.env.SITE_URL;
else process.env.SITE_URL = configuredSite;
console.log("Origin checks passed for rewritten local URLs, missing origins and canonical HTTPS origins.");
